### PR TITLE
tskit v0.3.5

### LINKED ISSUE #18: Drop h5py dependency
For the upcoming python 0.3.5 release of tskit we drop h5py as a mandatory dependency. We should remove it from the conda recipe too.

### PR DESCRIPTION
**Pull request by benjeffery**
Fixes #18 

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by benjeffery** [comment]
@conda-forge-admin, please rerender

**Comment by jeromekelleher** [comment]
Need to ``  skip: true  # [py<37]`` I think?

**Comment by benjeffery** [comment]
> skip: true # [py<37]

Good timing, I was just getting lost in the docs! Looked like a comment, didn't realise it was actually doing something!

**Comment by benjeffery** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
